# Generated by Django 6.0.4 on 2026-04-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="capacity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
